import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Header} from "../components/Header/Header";
import {fetchCurrencies} from "./api/currency";
import {FormConverter} from "../components/FormConverter/FormConverter";

export default function Home({currencies}) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Conventer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header currencies={currencies} />
        <FormConverter currencies={currencies} />
      </main>

    </div>
  )
}

export async function getServerSideProps () {

  const res = await fetchCurrencies();
  if(res.data){
    return { props: { currencies: res.data } };
  }


  return "Error server"
}

